fsc/fsc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_webapp.urls')),
]

fsc/messaging/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from .views import ThreadView, InboxView

app_name = 'messages'
urlpatterns = [
    path("", InboxView.as_view()),
    url(r"^(?P<username>[\w.@+-]+)", ThreadView.as_view()),
]

fsc/messaging/models.py
from django.db import models

from django.conf import settings
from django.db import models
from django.db.models import Q


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username): # get_or_create
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                        first=user, 
                        second=user2
                    )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    first        = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second       = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    updated      = models.DateTimeField(auto_now=True)
    timestamp    = models.DateTimeField(auto_now_add=True)
    
    objects      = ThreadManager()

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True
        return False


class ChatMessage(models.Model):
    thread      = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user        = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message     = models.TextField()
    timestamp   = models.DateTimeField(auto_now_add=True)

fsc/messaging/forms.py
from django import forms

class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                # attrs={"class": "form-control"}
                )
            )

fsc/messaging/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.edit import FormMixin

from django.views.generic import DetailView, ListView

from .forms import ComposeForm
from .models import Thread, ChatMessage


class InboxView(LoginRequiredMixin, ListView):
    template_name = 'messaging/inbox.html'
    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_name'] = "Inbox"
        return context


class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'messaging/thread_list.html'
    form_class = ComposeForm
    success_url = './'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username  = self.kwargs.get("username")
        obj, created    = Thread.objects.get_or_new(self.request.user, other_username)
        if obj == None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        context['page_name'] = self.kwargs.get("username")
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

    def get_success_url(self):

        url = super().get_success_url()
        url = url + self.kwargs.get("username")
        return url

fsc/messaging/templates/messaging/inbox.html
{% extends "main_webapp/base.html" %}

{% block content %}


{% endblock %}

fsc/messaging/templates/messaging/thread_list.html
{% extends "main_webapp/base.html" %}

{% block content %}
<h3>Thread for {% if user != object.first %}{{ object.first.username }}{% else %}{{ object.second.username }}{% endif %}</h3>
<ul id='chat-items'>
{% for chat in object.chatmessage_set.all %}

<li>{{ chat.message }} - {{ chat.user.username }}</li>

{% endfor %}
</ul>

<form id='form' method='POST'> {% csrf_token %}
{{form.as_p }}
<input type='submit' class='btn btn-primary'/>
</form>

<script>
    
    // websocket scripts
    
    loc = window.location
    var wsStart = 'ws://'

    if(loc.protocol == 'https:'){
        var wsStart =  'wss://'
    }

    var endpoint = wsStart + loc.host + loc.pathname
    var socket = new ReconnectingWebSocket(endpoint)
    var formData = $("#form")
    var msgInput = $("#id_message")
    var chatHolder = $("#chat-items")

    socket.onmessage = function(e){
        console.log("message", e)
        var chatdataMsg = JSON.parse(e.data)
        chatHolder.append("<li>" + chatdataMsg.message + " - " + chatdataMsg.username + "</li>")
    }

    socket.onopen = function(e){
        console.log("open", e)
        formData.submit(function(event){
            event.preventDefault()
            msg = msgInput.val()
            // chatHolder.append("<li>" + msg  + " - {{ user.username }}" + "</li>")
            data = JSON.stringify({"message" : msg})
            socket.send(data)
            formData[0].reset()
        })
    }

    socket.onerror = function(e){
        console.log("error", e)

    }
    socket.onclose = function(e){
        console.log("close", e)
    }
    
    
</script>

{% endblock %}